# Boost Radio Power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# PHY Compatibility (Xiao only speaks 1M PHY)
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_PHY_CODED=n

# Enhanced BLE connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
