CONFIG_ZMK_BLE=y
CONFIG_SETTINGS=y

# Boost Radio Power
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# PHY Compatibility (Xiao only speaks 1M PHY)
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_PHY_CODED=n

# Enhanced BLE connection stability
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Central Battery Settings (Fetch peripheral battery levels for the dongle screen)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Dongle plugged into host should not sleep
CONFIG_ZMK_SLEEP=n
