include:
  # --- Totem (Split Keyboard With Dongle) ---
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact_name: totem-left-peripheral
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact_name: totem-right-peripheral
  - board: raytac_mdbt50q_rx
    shield: totem_dongle
    artifact_name: totem-dongle-central
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    artifact_name: totem-display-central

  # --- Toucan 2 (Standalone: Left is Central with Built-in Display) ---
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact_name: toucan-left-central
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    artifact_name: toucan-right-peripheral

  # --- Toucan (With Small Dongle) ---
  - board: raytac_mdbt50q_rx
    shield: toucan_dongle
    artifact_name: toucan-dongle-central

  # --- Utilities & Resets ---
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact_name: settings-reset
  - board: raytac_mdbt50q_rx
    shield: settings_reset
    artifact_name: raytac-settings-reset
