include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    artifact_name: totem-left
  - board: seeeduino_xiao_ble
    shield: totem_right
    artifact_name: totem-right
  - board: seeeduino_xiao_ble
    shield: totem_dongle dongle_screen
    artifact_name: totem-dongle
  - board: seeeduino_xiao_ble
    shield: toucan_left rgbled_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact_name: toucan-left
  - board: seeeduino_xiao_ble
    shield: toucan_right rgbled_adapter
    artifact_name: toucan-right
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact_name: settings-reset
  - board: raytac_mdbt50q_rx
    shield: toucan_dongle
    artifact_name: toucan-dongle
  - board: raytac_mdbt50q_rx
    shield: raytac_settings_reset
    artifact_name: raytac-settings-reset
