# Bluetooth Transmission Power & Stability
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
 
# Deep sleep timeout: 5 minutes (300,000 ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=300000
