CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_INPUT_SPLIT=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=n
CONFIG_ZMK_POINTING=n
# Satisfy dependencies for central_bas_proxy.c even if not used as a peripheral
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
