manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: beekeeb
      url-base: https://github.com/beekeeb
    - name: janpfischer
      url-base: https://github.com/janpfischer
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
    # Toucan keyboard support
    - name: zmk-keyboard-toucan
      remote: beekeeb
      revision: main
      import: config/west.yml 
      path: modules/zmk-keyboard-toucan 

  self:
    path: config
