manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: beekeeb
      url-base: https://github.com/beekeeb
    - name: janpfischer
      url-base: https://github.com/janpfischer
    - name: rschenk
      url-base: https://github.com/rschenk
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
    - name: zmk-component-raytac-dongle
      remote: rschenk
      revision: v0.3
      path: modules/zmk-component-raytac-dongle
    - name: zmk-keyboard-toucan
      remote: beekeeb
      revision: main
      import: config/west.yml 
      path: modules/zmk-keyboard-toucan 
  self:
    path: config
