manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: beekeeb
      url-base: https://github.com/beekeeb
    - name: janpfischer
      url-base: https://github.com/janpfischer
    - name: rschenk
      url-base: https://github.com/rschenk
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: geeksville
      url-base: https://github.com/geeksville
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
      path: modules/zmk-dongle-screen
    - name: zmk-component-raytac-dongle
      remote: rschenk
      path: modules/zmk-component-raytac-dongle
    - name: zmk-keyboard-toucan
      remote: beekeeb
      revision: main
      import: config/west.yml 
      path: modules/zmk-keyboard-toucan 
    - name: cirque-input-module
      remote: geeksville
      revision: toucan
      path: modules/cirque-input-module
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3
      path: modules/zmk-rgbled-widget
  self:
    path: config
