file_format: "1"
id: toucan_left_peripheral
name: Toucan Left Peripheral
type: shield
url: https://github.com/beekeeb/zmk-keyboard-toucan
requires: [seeeduino_xiao_ble]
features:
  - keys
  - display
  - studio
